services:
  web:
    image: ghcr.io/zerotech-studio/homepage:latest
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        
        # Main router for HTTPS
        - traefik.http.routers.homepage.rule=Host(`zerotech.studio`)
        - traefik.http.routers.homepage.entrypoints=https
        - traefik.http.routers.homepage.tls=true
        - traefik.http.routers.homepage.tls.certresolver=le
        - traefik.http.services.homepage.loadbalancer.server.port=80
        
        # HTTP to HTTPS redirect
        - traefik.http.routers.homepage-http.rule=Host(`zerotech.studio`)
        - traefik.http.routers.homepage-http.entrypoints=http
        - traefik.http.routers.homepage-http.middlewares=https-redirect

networks:
  traefik-public:
    external: true 